public with sharing class fieldWrapper {
    //{"id":0,"label":"Test","apiName":"Test__c","type":"text","textLength":"23","defaultvalue":"",
    //"relationshipLabel":"","relationshipName":"","referenceTo":""}
    public String id;
    public String label;
    public String apiName;
    public String type;
    public String textLength;
    public String defaultvalue;
    public String relationshipLabel;
    public String relationshipName;
    public String referenceTo;
    public String visibleLines;
    public String scale;
    public fieldWrapper() {

    }
}